const API_BASE=window.location.hostname==="thomasjoseph18.github.io"?"https://farekeralam.onrender.com/api":"/api";
const API={health:`${API_BASE}/health`,classification:`${API_BASE}/government-classification`,vehicles:`${API_BASE}/vehicles`,calculate:`${API_BASE}/fare/calculate`};
const $=id=>document.getElementById(id);
const state={classes:[],categories:[],vehicles:[],loading:false};
const bool=v=>v===true||v===1||v==="1"||v==="true"||v==="TRUE";
const show=(e,on)=>{if(e)e.style.display=on?"":"none"};
const fmt=v=>{const n=Number(v);return Number.isFinite(n)?n.toFixed(2):"0.00"};
const placeholder=(s,t)=>{s.innerHTML="";const o=document.createElement("option");o.value="";o.textContent=t;o.disabled=true;o.selected=true;s.appendChild(o)};
async function api(url,opt={}){const r=await fetch(url,{...opt,mode:"cors",headers:{Accept:"application/json",...(opt.body?{"Content-Type":"application/json"}:{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){}if(!r.ok)throw Error(typeof d?.detail==="string"?d.detail:`API error ${r.status}`);return d}
function cls(){return state.classes.find(x=>Number(x.id)===Number($("governmentClass")?.value))}
function sub(){return cls()?.subclasses?.find(x=>Number(x.id)===Number($("governmentSubclass")?.value))}
function cfg(){return sub()?.configurations?.find(x=>Number(x.id)===Number($("governmentConfiguration")?.value))}
function mapped(){return cfg()?.vehicle_categories?.[0]||sub()?.vehicle_categories?.[0]||null}
function populateClasses(){const s=$("governmentClass");if(!s)return;placeholder(s,"Select government class");state.classes.forEach(x=>{const o=document.createElement("option");o.value=x.id;o.textContent=x.name;s.appendChild(o)})}
function populateSubclasses(){const c=cls(),s=$("governmentSubclass");if(!s)return;placeholder(s,"Select government subclass");(c?.subclasses||[]).forEach(x=>{const o=document.createElement("option");o.value=x.id;o.textContent=x.name;s.appendChild(o)});show($("governmentSubclassGroup"),!!c);show($("governmentConfigurationGroup"),false);$("category").value="";updateOperational()}
function populateConfigurations(){const x=sub(),s=$("governmentConfiguration");if(!s)return;placeholder(s,"Select vehicle configuration");(x?.configurations||[]).forEach(v=>{const o=document.createElement("option");o.value=v.id;o.textContent=v.name;s.appendChild(o)});show($("governmentConfigurationGroup"),!!x?.configurations?.length);updateOperational()}
function updateOperational(){const m=mapped();$("category").value=m?.name||"";updateRequirements();populateVehicles()}
function updateRequirements(){const c=state.categories.find(x=>x.name===$("category").value),need=!!c&&bool(c.requires_seating_capacity);show($("seatingGroup"),need);show($("vehicleGroup"),!!c&&bool(c.requires_model));$("seating").required=need;const s=$("seating");placeholder(s,"Select seats");if(need){[...new Set(state.vehicles.filter(v=>Number(v.category_id)===Number(c.id)).map(v=>v.seating_capacity).filter(v=>v!=null))].sort((a,b)=>a-b).forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=`${v} seats`;s.appendChild(o)})}}
function populateVehicles(){const s=$("vehicle");if(!s)return;const c=state.categories.find(x=>x.name===$("category").value),seat=Number($("seating")?.value)||null;let list=state.vehicles;if(c)list=list.filter(v=>Number(v.category_id)===Number(c.id));if(seat)list=list.filter(v=>v.seating_capacity==null||Number(v.seating_capacity)===seat);placeholder(s,list.length?"Select vehicle model":"No matching vehicle");list.forEach(v=>{const o=document.createElement("option");o.value=v.id;o.textContent=v.seating_capacity!=null?`${v.name} — ${v.seating_capacity} seats`:v.name;s.appendChild(o)})}
function empty(){show($("resultEmpty"),true);show($("resultSuccess"),false);show($("resultError"),false)}
function err(m){if($("errorMessage"))$("errorMessage").textContent=m;show($("resultEmpty"),false);show($("resultSuccess"),false);show($("resultError"),true)}
function display(c){$("fareAmount").textContent=fmt(c.fare);$("resultCategory").textContent=c.category||"—";$("resultDistance").textContent=fmt(c.distance_km);$("resultSeats").textContent=c.seating_capacity!=null?`${c.seating_capacity} seats`:"—";$("resultVehicle").textContent=c.vehicle?.name||c.category||"—";$("calculationMethod").textContent=c.calculation_method==="database_fare_rule"?"Government fare rule":c.calculation_method||"—";$("minimumFare").textContent=fmt(c.minimum_fare);$("additionalDistance").textContent=fmt(c.additional_distance_km);$("additionalFare").textContent=fmt(c.additional_fare);$("fareRuleNote").textContent=c.fare_source==="database"?`Calculated from the database fare rule. ${c.government_reference||""}`:"This is a fallback estimate and is not an official fare.";$("heroVehicle").textContent=c.vehicle?.name||c.category||"—";$("heroDistance").textContent=`${fmt(c.distance_km)} km`;$("heroFare").textContent=`₹${fmt(c.fare)}`;if($("heroEnergy"))$("heroEnergy").textContent=c.government_reference||"Govt. fare rule";const b=$("slabBreakdown");b.innerHTML="";(c.slab_breakdown||[]).forEach(x=>{const d=document.createElement("div");d.className="slab-row";d.innerHTML=`<span>${fmt(x.from_km)}–${fmt(x.to_km)} km</span><strong>₹${fmt(x.amount)} <small>(${fmt(x.rate_per_km)}/km)</small></strong>`;b.appendChild(d)});show($("slabSection"),!!c.slab_breakdown?.length);show($("resultEmpty"),false);show($("resultSuccess"),true);show($("resultError"),false)}
async function calculate(){if(state.loading)return;const c=state.categories.find(x=>x.name===$("category").value),d=Number($("distance").value),seat=Number($("seating").value)||null,vid=Number($("vehicle").value)||null;if(!c)return err("Please select a government classification that has a Fare Keralam fare category.");if(!Number.isFinite(d)||d<=0)return err("Please enter a valid journey distance.");if(bool(c.requires_seating_capacity)&&!seat)return err("Please select the seating capacity.");const body={category:c.name,distance_km:d};if(seat)body.seating_capacity=seat;if(vid)body.vehicle_id=vid;state.loading=true;$("calculateBtn").disabled=true;try{const r=await api(API.calculate,{method:"POST",body:JSON.stringify(body)});if(!r?.success||!r.calculation)throw Error("Invalid fare calculation response");display(r.calculation)}catch(e){console.error(e);err(e.message||"Unable to calculate fare.")}finally{state.loading=false;$("calculateBtn").disabled=false}}
async function init(){const l=$("pageLoader");if($("currentYear"))$("currentYear").textContent=new Date().getFullYear();empty();try{const[h,g,c,v]=await Promise.all([api(API.health),api(API.classification),api(`${API_BASE}/categories`),api(API.vehicles)]);state.classes=g?.classes||[];state.categories=c?.categories||[];state.vehicles=v?.vehicles||[];populateClasses();$("categoryCount").textContent=state.categories.length;$("vehicleCount").textContent=state.vehicles.length;$("vehicleCountStat").textContent=state.vehicles.length;$("footerStatus").textContent=h?.status==="healthy"?"API online":"API unavailable";$("heroApiStatus").classList.toggle("online",h?.status==="healthy")}catch(e){console.error(e);$("footerStatus").textContent="API connection problem";err("The Fare Keralam classification could not be loaded. Run the database migration in Supabase, then refresh.")}finally{if(l){l.classList.add("hidden");setTimeout(()=>l.remove(),500)}}}
document.addEventListener("DOMContentLoaded",()=>{$("fareForm")?.addEventListener("submit",e=>{e.preventDefault();calculate()});$("governmentClass")?.addEventListener("change",populateSubclasses);$("governmentSubclass")?.addEventListener("change",populateConfigurations);$("governmentConfiguration")?.addEventListener("change",updateOperational);$("seating")?.addEventListener("change",populateVehicles);$("resetBtn")?.addEventListener("click",()=>{$("fareForm")?.reset();empty();show($("governmentSubclassGroup"),false);show($("governmentConfigurationGroup"),false)});$("retryBtn")?.addEventListener("click",calculate);$("mobileMenuBtn")?.addEventListener("click",()=>$("mainNav")?.classList.toggle("open"));init()});