-- ============================================================
-- FARE KERALAM V1
-- SOURCE-INTEGRATED DATABASE
-- PostgreSQL / Supabase
-- NO GPT
-- ============================================================

CREATE TABLE IF NOT EXISTS vehicle_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    requires_model BOOLEAN NOT NULL DEFAULT FALSE,
    requires_seating_capacity BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS energy_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    unit TEXT NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL
        REFERENCES vehicle_categories(id)
        ON DELETE RESTRICT,
    energy_source_id BIGINT
        REFERENCES energy_sources(id)
        ON DELETE RESTRICT,
    name TEXT,
    seating_capacity INTEGER,
    efficiency NUMERIC(12,4),
    efficiency_unit TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (seating_capacity IS NULL OR seating_capacity > 0),
    CHECK (efficiency IS NULL OR efficiency > 0)
);

CREATE TABLE IF NOT EXISTS data_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    organization TEXT NOT NULL,
    url TEXT NOT NULL,
    data_type TEXT NOT NULL,
    source_level TEXT NOT NULL DEFAULT 'official'
        CHECK (
            source_level IN (
                'official',
                'government_statistics',
                'regulated',
                'market',
                'secondary'
            )
        ),
    update_frequency TEXT,
    automatic_update_supported BOOLEAN NOT NULL DEFAULT FALSE,
    verification_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (
            verification_status IN (
                'pending',
                'verified',
                'expired',
                'unavailable'
            )
        ),
    last_checked_at TIMESTAMPTZ,
    last_successful_update_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS source_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL
        REFERENCES data_sources(id)
        ON DELETE CASCADE,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status TEXT NOT NULL
        CHECK (
            status IN (
                'success',
                'failed',
                'changed',
                'unchanged',
                'manual_review'
            )
        ),
    records_added INTEGER NOT NULL DEFAULT 0,
    records_updated INTEGER NOT NULL DEFAULT 0,
    records_rejected INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS fare_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL
        REFERENCES vehicle_categories(id)
        ON DELETE RESTRICT,
    energy_source_id BIGINT
        REFERENCES energy_sources(id)
        ON DELETE RESTRICT,
    minimum_fare NUMERIC(12,2) NOT NULL,
    minimum_distance_km NUMERIC(10,2) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    source_id BIGINT
        REFERENCES data_sources(id)
        ON DELETE SET NULL,
    government_reference TEXT,
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'active', 'expired')),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (minimum_fare >= 0),
    CHECK (minimum_distance_km >= 0),
    CHECK (
        effective_to IS NULL
        OR effective_to >= effective_from
    )
);

CREATE TABLE IF NOT EXISTS fare_slabs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fare_rule_id BIGINT NOT NULL
        REFERENCES fare_rules(id)
        ON DELETE CASCADE,
    from_km NUMERIC(10,2) NOT NULL,
    to_km NUMERIC(10,2),
    rate_per_km NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (from_km >= 0),
    CHECK (to_km IS NULL OR to_km > from_km),
    CHECK (rate_per_km >= 0)
);

CREATE TABLE IF NOT EXISTS cost_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cost_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_category_id BIGINT NOT NULL
        REFERENCES cost_categories(id)
        ON DELETE RESTRICT,
    energy_source_id BIGINT
        REFERENCES energy_sources(id)
        ON DELETE SET NULL,
    value NUMERIC(14,4) NOT NULL,
    unit TEXT NOT NULL,
    location TEXT NOT NULL DEFAULT 'Kerala',
    district TEXT,
    effective_date DATE NOT NULL,
    source_id BIGINT
        REFERENCES data_sources(id)
        ON DELETE SET NULL,
    source_reference TEXT,
    retrieved_at TIMESTAMPTZ,
    verification_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (
            verification_status IN (
                'pending',
                'verified',
                'rejected'
            )
        ),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (value >= 0)
);

CREATE TABLE IF NOT EXISTS price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_category_id BIGINT NOT NULL
        REFERENCES cost_categories(id),
    energy_source_id BIGINT
        REFERENCES energy_sources(id)
        ON DELETE SET NULL,
    value NUMERIC(14,4) NOT NULL,
    unit TEXT NOT NULL,
    location TEXT NOT NULL DEFAULT 'Kerala',
    district TEXT,
    price_date DATE NOT NULL,
    source_id BIGINT
        REFERENCES data_sources(id)
        ON DELETE SET NULL,
    source_reference TEXT,
    retrieved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (value >= 0)
);

CREATE TABLE IF NOT EXISTS historical_fares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL
        REFERENCES vehicle_categories(id),
    energy_source_id BIGINT
        REFERENCES energy_sources(id),
    minimum_fare NUMERIC(12,2),
    minimum_distance_km NUMERIC(10,2),
    effective_from DATE NOT NULL,
    effective_to DATE,
    source_id BIGINT
        REFERENCES data_sources(id)
        ON DELETE SET NULL,
    government_reference TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cost_index_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_category_id BIGINT NOT NULL
        REFERENCES cost_categories(id),
    index_value NUMERIC(14,6) NOT NULL,
    reference_period DATE NOT NULL,
    location TEXT NOT NULL DEFAULT 'Kerala',
    source_id BIGINT
        REFERENCES data_sources(id)
        ON DELETE SET NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS calculation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT
        REFERENCES vehicle_categories(id)
        ON DELETE SET NULL,
    energy_source_id BIGINT
        REFERENCES energy_sources(id)
        ON DELETE SET NULL,
    vehicle_id BIGINT
        REFERENCES vehicles(id)
        ON DELETE SET NULL,
    distance_km NUMERIC(10,2) NOT NULL,
    official_fare NUMERIC(12,2),
    operating_cost_estimate NUMERIC(12,2),
    calculation_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (distance_km >= 0)
);

-- ============================================================
-- OFFICIAL / GOVERNMENT DATA SOURCES
-- ============================================================

INSERT INTO data_sources
(
    name,
    organization,
    url,
    data_type,
    source_level,
    update_frequency,
    automatic_update_supported,
    verification_status,
    notes
)
VALUES

(
    'Kerala Motor Vehicles Department',
    'Government of Kerala',
    'https://mvd.kerala.gov.in/',
    'Transport fares and government notifications',
    'official',
    'As published',
    FALSE,
    'verified',
    'Primary source for Kerala transport notifications.'
),

(
    'PPAC Petrol and Diesel RSP',
    'Petroleum Planning & Analysis Cell, Ministry of Petroleum & Natural Gas',
    'https://ppac.gov.in/retail-selling-price-rsp-of-petrol-diesel-and-domestic-lpg/price-build-up-of-petrol-and-diesel',
    'Petrol and diesel retail selling price',
    'official',
    'Daily / as published',
    TRUE,
    'verified',
    'Government of India petroleum price source.'
),

(
    'PNGRB CNG Prices',
    'Petroleum and Natural Gas Regulatory Board',
    'https://pngrb.gov.in/eng-web/consumer-awareness.html',
    'CNG retail selling prices',
    'regulated',
    'Periodic',
    TRUE,
    'verified',
    'CNG prices by geographical area.'
),

(
    'Kerala Department of Economics and Statistics',
    'Government of Kerala',
    'https://www.ecostat.kerala.gov.in/',
    'Kerala price statistics',
    'government_statistics',
    'Daily / weekly / monthly depending on dataset',
    FALSE,
    'verified',
    'Kerala state price statistics.'
),

(
    'Kerala Ecostat Daily Price Dashboard',
    'Department of Economics and Statistics, Government of Kerala',
    'https://www.ecostat.kerala.gov.in/state-dashboard-prices-of-essential-commodities',
    'Daily Kerala retail price statistics',
    'government_statistics',
    'Daily working days',
    FALSE,
    'verified',
    'State and district-level price information.'
),

(
    'Kerala State Electricity Regulatory Commission',
    'Government of Kerala',
    'https://kserc.kerala.gov.in/',
    'Electricity tariff orders',
    'official',
    'As notified',
    FALSE,
    'pending',
    'Electricity tariff information.'
)

ON CONFLICT DO NOTHING;

-- ============================================================
-- VEHICLE CATEGORIES
-- ============================================================

INSERT INTO vehicle_categories
(
    name,
    description,
    requires_model,
    requires_seating_capacity
)
VALUES

(
    'Auto Rickshaw',
    'Three-wheeled passenger auto-rickshaw',
    FALSE,
    FALSE
),

(
    'Taxi / Motor Cab',
    'Passenger taxi or motor cab',
    TRUE,
    FALSE
),

(
    'Maxicab',
    'Passenger vehicle classified as maxicab',
    FALSE,
    TRUE
),

(
    'Traveller',
    'Passenger traveller / van',
    FALSE,
    TRUE
),

(
    'Route Bus',
    'Regular stage/route carriage bus',
    FALSE,
    FALSE
),

(
    'Tourist Bus',
    'Tourist passenger bus',
    FALSE,
    TRUE
)

ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- ENERGY SOURCES
-- ============================================================

INSERT INTO energy_sources
(
    name,
    unit,
    description
)
VALUES

(
    'Petrol',
    'litre',
    'Petrol / gasoline'
),

(
    'Diesel',
    'litre',
    'Diesel fuel'
),

(
    'CNG',
    'kg',
    'Compressed natural gas'
),

(
    'Electricity',
    'kWh',
    'Electrical energy'
),

(
    'Hybrid',
    'mixed',
    'Hybrid energy system'
)

ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- COST CATEGORIES
-- ============================================================

INSERT INTO cost_categories
(
    name,
    description
)
VALUES

(
    'Petrol',
    'Petrol fuel cost'
),

(
    'Diesel',
    'Diesel fuel cost'
),

(
    'CNG',
    'Compressed natural gas cost'
),

(
    'Electricity',
    'Electricity / EV charging cost'
),

(
    'Tyres',
    'Tyres and tubes'
),

(
    'Lubricants',
    'Engine oil and other lubricants'
),

(
    'Maintenance',
    'Vehicle maintenance and repairs'
),

(
    'Other Operating Costs',
    'Other vehicle operating expenses'
),

(
    'Inflation',
    'General price-level change'
)

ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_vehicles_category
    ON vehicles(category_id);

CREATE INDEX IF NOT EXISTS idx_vehicles_energy
    ON vehicles(energy_source_id);

CREATE INDEX IF NOT EXISTS idx_fare_rules_category
    ON fare_rules(category_id);

CREATE INDEX IF NOT EXISTS idx_fare_rules_dates
    ON fare_rules(effective_from, effective_to);

CREATE INDEX IF NOT EXISTS idx_fare_slabs_rule
    ON fare_slabs(fare_rule_id);

CREATE INDEX IF NOT EXISTS idx_cost_data_category
    ON cost_data(cost_category_id);

CREATE INDEX IF NOT EXISTS idx_cost_data_date
    ON cost_data(effective_date);

CREATE INDEX IF NOT EXISTS idx_cost_data_location
    ON cost_data(location, district);

CREATE INDEX IF NOT EXISTS idx_price_history_date
    ON price_history(price_date);

CREATE INDEX IF NOT EXISTS idx_price_history_location
    ON price_history(location, district);

CREATE INDEX IF NOT EXISTS idx_historical_fares_category
    ON historical_fares(category_id);

CREATE INDEX IF NOT EXISTS idx_source_updates_source
    ON source_updates(source_id);