-- ============================================================
-- FARE KERALAM - GOVERNMENT VEHICLE CLASSIFICATION
-- Adds the hierarchical government-oriented classification used
-- by the passenger-facing calculator.
-- ============================================================

CREATE TABLE IF NOT EXISTS government_vehicle_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS government_vehicle_subclasses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL REFERENCES government_vehicle_classes(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (class_id, name)
);

CREATE TABLE IF NOT EXISTS government_vehicle_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subclass_id BIGINT NOT NULL REFERENCES government_vehicle_subclasses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (subclass_id, name)
);

-- Links a government classification node to the Fare Keralam
-- operational category when a matching fare category exists.
CREATE TABLE IF NOT EXISTS government_vehicle_category_map (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subclass_id BIGINT REFERENCES government_vehicle_subclasses(id) ON DELETE CASCADE,
    configuration_id BIGINT REFERENCES government_vehicle_configurations(id) ON DELETE CASCADE,
    vehicle_category_id BIGINT NOT NULL REFERENCES vehicle_categories(id) ON DELETE RESTRICT,
    notes TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (subclass_id IS NOT NULL OR configuration_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_gov_vehicle_subclasses_class
    ON government_vehicle_subclasses(class_id);
CREATE INDEX IF NOT EXISTS idx_gov_vehicle_configurations_subclass
    ON government_vehicle_configurations(subclass_id);
CREATE INDEX IF NOT EXISTS idx_gov_vehicle_category_map_subclass
    ON government_vehicle_category_map(subclass_id);
CREATE INDEX IF NOT EXISTS idx_gov_vehicle_category_map_configuration
    ON government_vehicle_category_map(configuration_id);

-- ------------------------------------------------------------
-- Top-level classes
-- ------------------------------------------------------------
INSERT INTO government_vehicle_classes (name, description, display_order)
VALUES
('Hire / Contract Carriage', 'Hire and contract carriage vehicle classifications used by Fare Keralam.', 1),
('Stage Carriage', 'Stage carriage service classifications used by Fare Keralam.', 2)
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description, display_order = EXCLUDED.display_order;

-- ------------------------------------------------------------
-- Hire / Contract Carriage subclasses
-- ------------------------------------------------------------
INSERT INTO government_vehicle_subclasses (class_id, name, description, display_order)
SELECT id, v.name, v.description, v.display_order
FROM government_vehicle_classes c
CROSS JOIN (VALUES
    ('Auto Rickshaw', 'Three-wheeled passenger auto-rickshaw.', 1),
    ('Quadricycle', 'Quadricycle passenger vehicle classification.', 2),
    ('Motor Cab / Taxi', 'Passenger motor cab / taxi classification.', 3),
    ('Maxicab', 'Passenger vehicle classified as a maxicab.', 4),
    ('Contract Carriage', 'Contract carriage classification.', 5)
) AS v(name, description, display_order)
WHERE c.name = 'Hire / Contract Carriage'
ON CONFLICT (class_id, name) DO UPDATE SET description = EXCLUDED.description, display_order = EXCLUDED.display_order;

-- Contract-carriage child node requested for Traveller vehicles.
INSERT INTO government_vehicle_configurations (subclass_id, name, description, display_order)
SELECT s.id, 'Traveller / Contract vehicles', 'Traveller and other contract passenger vehicles.', 1
FROM government_vehicle_subclasses s
JOIN government_vehicle_classes c ON c.id = s.class_id
WHERE c.name = 'Hire / Contract Carriage' AND s.name = 'Contract Carriage'
ON CONFLICT (subclass_id, name) DO UPDATE SET description = EXCLUDED.description, display_order = EXCLUDED.display_order;

-- ------------------------------------------------------------
-- Stage Carriage subclasses
-- ------------------------------------------------------------
INSERT INTO government_vehicle_subclasses (class_id, name, description, display_order)
SELECT id, v.name, v.description, v.display_order
FROM government_vehicle_classes c
CROSS JOIN (VALUES
    ('Ordinary / Mofussil', 'Ordinary / mofussil stage carriage service.', 1),
    ('City Fast', 'City fast stage carriage service.', 2),
    ('Fast Passenger / Limited Stop', 'Fast passenger / limited-stop service.', 3),
    ('Super Fast', 'Super fast stage carriage service.', 4),
    ('Express', 'Express stage carriage service.', 5),
    ('Super Express', 'Super express stage carriage service.', 6),
    ('Super Air Express', 'Super air express stage carriage service.', 7),
    ('Super Deluxe / Semi Sleeper', 'Super deluxe / semi-sleeper service.', 8),
    ('Luxury / High-Tech / AC', 'Luxury, high-tech and air-conditioned service.', 9)
) AS v(name, description, display_order)
WHERE c.name = 'Stage Carriage'
ON CONFLICT (class_id, name) DO UPDATE SET description = EXCLUDED.description, display_order = EXCLUDED.display_order;

-- Configuration options under the Luxury / High-Tech / AC subclass.
INSERT INTO government_vehicle_configurations (subclass_id, name, description, display_order)
SELECT s.id, v.name, v.description, v.display_order
FROM government_vehicle_subclasses s
JOIN government_vehicle_classes c ON c.id = s.class_id
CROSS JOIN (VALUES
    ('Single Axle', 'Single-axle bus configuration.', 1),
    ('Multi Axle', 'Multi-axle bus configuration.', 2),
    ('Low Floor AC', 'Low-floor air-conditioned configuration.', 3),
    ('Low Floor Non-AC', 'Low-floor non-air-conditioned configuration.', 4)
) AS v(name, description, display_order)
WHERE c.name = 'Stage Carriage' AND s.name = 'Luxury / High-Tech / AC'
ON CONFLICT (subclass_id, name) DO UPDATE SET description = EXCLUDED.description, display_order = EXCLUDED.display_order;

-- ------------------------------------------------------------
-- Existing Fare Keralam category mappings.
-- These mappings do not invent fare rules for classifications that
-- are not yet represented by an operational category/fare rule.
-- ------------------------------------------------------------
INSERT INTO government_vehicle_category_map (subclass_id, vehicle_category_id, notes)
SELECT s.id, vc.id, 'Mapped to existing Fare Keralam Auto Rickshaw category.'
FROM government_vehicle_subclasses s
JOIN government_vehicle_classes c ON c.id = s.class_id
JOIN vehicle_categories vc ON vc.name = 'Auto Rickshaw'
WHERE c.name = 'Hire / Contract Carriage' AND s.name = 'Auto Rickshaw'
  AND NOT EXISTS (SELECT 1 FROM government_vehicle_category_map m WHERE m.subclass_id=s.id AND m.vehicle_category_id=vc.id)
ON CONFLICT DO NOTHING;

INSERT INTO government_vehicle_category_map (subclass_id, vehicle_category_id, notes)
SELECT s.id, vc.id, 'Mapped to existing Fare Keralam Taxi / Motor Cab category.'
FROM government_vehicle_subclasses s
JOIN government_vehicle_classes c ON c.id = s.class_id
JOIN vehicle_categories vc ON vc.name = 'Taxi / Motor Cab'
WHERE c.name = 'Hire / Contract Carriage' AND s.name = 'Motor Cab / Taxi'
  AND NOT EXISTS (SELECT 1 FROM government_vehicle_category_map m WHERE m.subclass_id=s.id AND m.vehicle_category_id=vc.id)
ON CONFLICT DO NOTHING;

INSERT INTO government_vehicle_category_map (subclass_id, vehicle_category_id, notes)
SELECT s.id, vc.id, 'Mapped to existing Fare Keralam Maxicab category.'
FROM government_vehicle_subclasses s
JOIN government_vehicle_classes c ON c.id = s.class_id
JOIN vehicle_categories vc ON vc.name = 'Maxicab'
WHERE c.name = 'Hire / Contract Carriage' AND s.name = 'Maxicab'
  AND NOT EXISTS (SELECT 1 FROM government_vehicle_category_map m WHERE m.subclass_id=s.id AND m.vehicle_category_id=vc.id)
ON CONFLICT DO NOTHING;

INSERT INTO government_vehicle_category_map (configuration_id, vehicle_category_id, notes)
SELECT cfg.id, vc.id, 'Mapped to existing Fare Keralam Traveller category.'
FROM government_vehicle_configurations cfg
JOIN government_vehicle_subclasses s ON s.id=cfg.subclass_id
JOIN government_vehicle_classes c ON c.id=s.class_id
JOIN vehicle_categories vc ON vc.name='Traveller'
WHERE c.name='Hire / Contract Carriage' AND s.name='Contract Carriage' AND cfg.name='Traveller / Contract vehicles'
  AND NOT EXISTS (SELECT 1 FROM government_vehicle_category_map m WHERE m.configuration_id=cfg.id AND m.vehicle_category_id=vc.id)
ON CONFLICT DO NOTHING;

-- Note: Quadricycle and the stage-carriage service subclasses remain
-- unmapped until their corresponding operational categories and fare
-- rules are entered. The frontend must not manufacture a fare for them.
