/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hkzqrokepzvbvsdgnpsa"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrenFyb2tlcHp2YnZzZGducHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYxNzAwMTQsImV4cCI6MjEwMTc0NjAxNH0.lXYl-IyFt0zvZa9_KqnJ3ATj_trje-PXztlPwGHRQIU"